name: Build Docker Image

on:
    push:
        branchs: ["master"]
    pull_request:
        branchs: ["master"]
 
jobs: 
    build-docker: 
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v2
            - run: docker build -t lelyabot .